# Algorithm 3: Analyst Agent Expert Analysis (AAEA)

import re
from pre_prompt import client, persona, common_mistakes_db, ana_task
from usage_logger import log_usage

def AAEA(lesson_plan: str) -> str:
    """
    Analyst Agent Expert Analysis (AAEA)
    Input:
        - lesson_plan: Instructional Design (Lp) with Example Questions (EQs)
          generated by Optimizer Agent
        - Common Mistakes Database (CMD)
        - Knowledge Background (KB)
    Output:
        - nlp: new instructional designs with integrated error-prone points and probabilities
    """

    # Step 1: Initialize Analyst Agent (A_a)
    # Step 2: EQs <- Retrieve example questions from Lp
    # Step 3: Load CMD

    # Step 4-11: For each eq in EQs, identify KB, retrieve top 3 common mistakes,
    #            calculate mistake probability, generate explanation,
    #            sort CMs by mp descending, insert into eq section of Lp
    analysis_prompt = f"""You are an expert Question Analyst.

Student Knowledge Background:
{persona}

Common Mistakes Database (CMD):
{common_mistakes_db}

{lesson_plan}

{ana_task}
"""

    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {"role": "system", "content": "You are a helpful assistant."},
            {"role": "user", "content": analysis_prompt},
        ],
        temperature=0.7,
        max_tokens=2048,
    )
    log_usage(response,"gpt-4o")

    # Step 12: return nlp
    nlp = response.choices[0].message.content
    return nlp